### ISSUE TITLE
Feature request: Automatically save to a file on changes

### ISSUE THREAD

**Issue by TamasBarta** [rotemdan/ExportCookies#7]
Hi!
Love this extension. It would be nice, if the extension would allow to save to a specific file specific domains' cookies, so it had a one-way sync. That way, I wouldn't have to save manually every time my cookies expire. What do you think?
Thanks!

**Comment by rotemdan** [comment]
Hi, thanks for the suggestion. Sorry for the delayed response.

In order to write a file to disk, the Web / Extension API requires that a "Save.." dialog is opened to prompt the user to a file location. I'm not aware of a way to write directly to disk without any user consent (I imagine that might possibly become a security issue - say - that files are being written / overwritten with arbitrary data without the user knowing).

The extension is also very privacy sensitive by nature and has been reviewed by the Mozilla staff several times (requiring me, for example, to use exact, unminified versions of its dependent libraries). At some point it also got disabled on the Chrome store (It doesn't satisfy their privacy policies - though they didn't give any more specific reasons).

I feel adding a feature of this kind (given it is technically possible to do) would risk the extension appearing too privacy-intrusive and possibly getting banned, unfortunately.

**Comment by TamasBarta** [comment]
I see. Thanks for the explanation. I guess we can close this then.
