### ISSUE TITLE
Not working in Chrome 

### ISSUE THREAD

**Issue by danjaredg** [rotemdan/ExportCookies#8]
This extension https://chrome.google.com/webstore/detail/export-cookies/fhdkeghnanjflkiaincdogejojhjbkni not working in chrome, but the fix is very simple, you only need delete firstPartyDomain parameter from popup.js file

![imagen](https://user-images.githubusercontent.com/2866615/106970650-f7d5fa80-6712-11eb-8491-52f24ecf8d28.png)

**Comment by rotemdan** [comment]
Hi, the extension has been blocked from the Chrome Web Store for several years! (I was not provided any explanations). They seem to have unblocked it now. During the time it was blocked I was not able to update it. The version that you're seeing is older than the one for Firefox and needs updating. I will look at the particular modification you recommend as well. Thank you.

**Comment by rotemdan** [comment]
The `firstPartyDomain: null` parameter is required for supporting first party isolation in Firefox. It was added to resolve issue #5. Here is some more info:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll#parameters

Seems like latest Chrome doesn't like the extra parameter it doesn't recognize. I'm not sure what to do about it since the extension was designed to support both browsers (I prefer not to use browser specific checks unless absolutely needed). 

I will unpublish from the chrome web store until I find a solution.

**Comment by rotemdan** [comment]
Update: The extension is still blocked on the Chrome Store. I have unpublished it but I have no idea why the link you provided is still working. Could be a recent change or due to a bug in the Store. There is no way for me to disable the store entry I can't pubish a new version of the extension.

**Comment by louie-github** [comment]
Just an update, the [link](https://chrome.google.com/webstore/detail/export-cookies/gnkljdjnepojcjhhaoledinfjmampdcd) errors out now with a 404.

Latest Chrome Dev (Version 92.0.4491.6 (Official Build) dev (64-bit)) still errors out when trying to export because it doesn't recognize the parameter. Removing all instances of `firstPartyDomain` still fixes errors and allows for export.
